# Simply commit anything to main or other branches and trigger the deployment
# Go to your repository’s Settings → Pages.
# Under Build and deployment, select “GitHub Actions” as the deployment source.
# After the workflow runs, change the branch to gh-pages branch for GitHub Pages to serve your site
name: Deploy to GH Pages
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
